---
version: '3.7'
services:
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - /opt/eastecho/certbot/conf:/etc/letsencrypt
      - /opt/eastecho/certbot/www:/var/www/certbot
  eastecho:
    restart: always
    image: eastecho:latest
    command: uwsgi --ini /etc/uwsgi.ini --static-map /static=/opt/eastecho/static
    volumes:
      - /opt/eastecho/media:/opt/eastecho/media
    depends_on:
      - memcached
      - postgres
    expose:
      - 8000
    links:
      - memcached
      - postgres
  memcached:
    image: memcached
    restart: always
    expose:
      - 11211
  migrate:
    restart: "no"
    image: eastecho:latest
    command: /usr/local/bin/migrate.sh
    links:
      - postgres
  nginx:
    image: eastecho-nginx:latest
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx'"
    links:
      - eastecho
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/eastecho/certbot/conf:/etc/letsencrypt
      - /opt/eastecho/certbot/www:/var/www/certbot
      - /opt/eastecho/media:/opt/eastecho/media
  postgres:
    image: postgres:11
    expose:
      - 5432
    volumes:
      - /opt/eastecho/postgresql:/var/lib/postgresql/data

